/**
 * @file Version.h
 * @brief Version information for ADS1115.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef ADS1115_VERSION_STRING
#define ADS1115_VERSION_STRING "0.3.0"
#endif

#ifndef ADS1115_BUILD_DATE
#define ADS1115_BUILD_DATE __DATE__
#endif

#ifndef ADS1115_BUILD_TIME
#define ADS1115_BUILD_TIME __TIME__
#endif

#ifndef ADS1115_BUILD_TIMESTAMP
#define ADS1115_BUILD_TIMESTAMP ADS1115_BUILD_DATE " " ADS1115_BUILD_TIME
#endif

#ifndef ADS1115_GIT_COMMIT
#define ADS1115_GIT_COMMIT "unknown"
#endif

#ifndef ADS1115_GIT_STATUS
#define ADS1115_GIT_STATUS "unknown"
#endif

#ifndef ADS1115_VERSION_FULL
#define ADS1115_VERSION_FULL ADS1115_VERSION_STRING " (" ADS1115_GIT_COMMIT ", " ADS1115_BUILD_TIMESTAMP ", " ADS1115_GIT_STATUS ")"
#endif

namespace ADS1115 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 0;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 3;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = ADS1115_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 300;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 300;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = ADS1115_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = ADS1115_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = ADS1115_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = ADS1115_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = ADS1115_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = ADS1115_VERSION_FULL;

}  // namespace ADS1115
